export type TabType = 'CHAT' | 'TASKS' | 'WORKSPACE' | 'SKILLS' | 'ACTIVITY' | 'PROFILE';

/** Message role in a conversation */
export type MessageRole = "user" | "agent" | "system";

/** Agent identifier */
export type AgentId = string;

export interface Agent {
  id: string;
  name: string;
  description: string;
  status: 'online' | 'offline' | 'busy';
  avatar: string;
  color: string;
}

// ===========================================================================
// Channel types
// ===========================================================================

/** A collaboration channel containing multiple Agent members. */
export interface Channel {
  id: string;
  name: string;
  members: ChannelMember[];
  messages: ChannelMessage[];
  /** Compressed summary of older messages (generated by Agent runtime) */
  summary?: string | null;
  /** Message ID up to which messages have been summarized */
  summary_up_to?: string | null;
  /** When the summary was last updated */
  summary_updated_at?: string | null;
  created_at: string;
  updated_at: string;
}

/** A member (Agent) in a channel. */
export interface ChannelMember {
  agent_id: string;
  role: string;
  joined_at: string;
}

/** A message within a channel. */
export interface ChannelMessage {
  id: string;
  channel_id: string;
  sender_type: "user" | "agent";
  sender_id: string;
  content: string;
  timestamp: string;
}

/** Lightweight channel info for listing. */
export interface ChannelInfo {
  id: string;
  name: string;
  member_count: number;
  unread_count: number;
  preview: string;
  message_count: number;
  created_at: string;
  updated_at: string;
}

export interface Thread {
  id: string;
  agent_id: string;
  title: string;
  session_id: string | null;
  messages: ThreadMessageData[];
  created_at: string;
  updated_at: string;
}

export interface ThreadMessageData {
  id: string;
  role: "user" | "agent";
  content: string;
  timestamp: string;
}

export interface ThreadInfo {
  id: string;
  agent_id: string;
  title: string;
  preview: string;
  message_count: number;
  created_at: string;
  updated_at: string;
}

export interface Task {
  id: number;
  title: string;
  status: 'TODO' | 'IN PROGRESS' | 'IN REVIEW' | 'DONE';
  assignee?: string;
}

export interface Message {
  id: string;
  sender: {
    name: string;
    avatar: string;
    isAgent: boolean;
  };
  content: string;
  timestamp: string;
  isThinking?: boolean;
}

// ===========================================================================
// Agent Runtime types
// ===========================================================================

/** Agent runtime type enum */
export type RuntimeType =
  | "claude_code"
  | "codex"
  | "gemini"
  | string; // custom runtime types

/** Agent runtime status */
export type AgentRuntimeStatusType =
  | "available"
  | "unhealthy"
  | "not-installed"
  | "detecting";

/** Agent runtime capability */
export type AgentCapability =
  | "streaming"
  | "sessions"
  | "tool_use"
  | "structured_output";

/** Information about a registered agent runtime */
export interface AgentRuntimeInfo {
  id: string;
  name: string;
  runtime_category: string;
  runtime_type: RuntimeType;
  status: AgentRuntimeStatusType;
  version?: string;
  install_path?: string;
  capabilities: AgentCapability[];
  install_hint: string;
  binary_name?: string;
}

/** Streaming event from an agent runtime execution */
export interface StreamEvent {
  text: string;
  is_done: boolean;
  error?: string;
  type?: string;
  session_id?: string;
}

/** Channel streaming chunk event (wraps StreamEvent with agent context) */
export interface ChannelChunkEvent {
  channel_id: string;
  agent_id: string;
  agent_index: number;
  total_agents: number;
  event: StreamEvent;
}

/** Channel agent start event */
export interface ChannelAgentStartEvent {
  channel_id: string;
  agent_id: string;
  agent_index: number;
  total_agents: number;
}

/** Channel response event (after streaming completes) */
export interface ChannelResponseEvent {
  channel_id: string;
  agent_id: string;
  content: string;
  session_id: string | null;
}

/** Parsed @mention from a message */
export interface ParsedMention {
  raw: string;
  agent_id: string;
}

// ===========================================================================
// Agent Workspace types
// ===========================================================================

/** Agent summary returned from the backend */
export interface AgentSummary {
  agent_id: string;
  name: string;
  emoji: string;
  avatar: string | null;
  /** SVG icon name from the icon registry (e.g. "Bot", "Rocket") */
  icon: string | null;
  enabled: boolean;
  session_count: number;
  /** The runtime type this agent is bound to */
  runtime_type: RuntimeType;
}

/** Agent identity metadata */
export interface IdentitySummary {
  agent_id: string;
  name: string;
  emoji: string;
  avatar: string | null;
  /** SVG icon name from the icon registry */
  icon: string | null;
  creature: string;
  vibe: string;
  /** The runtime type this agent is bound to */
  runtime_type: RuntimeType;
}

/** Request to create a new Agent */
export interface CreateAgentRequest {
  name: string;
  creature?: string;
  vibe?: string;
  emoji?: string;
  avatar?: string;
  /** SVG icon name from the icon registry */
  icon?: string;
  /** Runtime type for the agent (defaults to "claude_code") */
  runtime_type?: RuntimeType;
}

/** Request to update an existing Agent's mutable properties */
export interface UpdateAgentRequest {
  name?: string;
  creature?: string;
  vibe?: string;
  emoji?: string;
  /** SVG icon name from the icon registry (empty string clears it) */
  icon?: string;
}

/** Workspace and Agent manager status */
export interface ManagerStatus {
  total_agents: number;
  enabled_agents: number;
  active_agent_id: string | null;
  workspace_root: string;
}

/** Result of workspace initialization */
export interface InitWorkspaceResult {
  templates_created: string[];
  templates_skipped: string[];
  default_created: boolean;
}

/** Agent context information (for debugging/preview) */
export interface AgentContextResult {
  agent_id: string;
  system_prompt: string;
  has_user_context: boolean;
  has_agent_instructions: boolean;
  has_tool_instructions: boolean;
  has_memory: boolean;
  has_history: boolean;
  context_prefix_length: number;
}

// ===========================================================================
// Agent with Runtime status types
// ===========================================================================

/** Agent summary fused with its runtime availability status */
export interface AgentWithRuntime {
  /** Agent workspace summary */
  agent: AgentSummary;
  /** Runtime status: "available" | "not-installed" | "unhealthy" | "detecting" */
  runtime_status: AgentRuntimeStatusType;
  /** Detected runtime version (if available) */
  runtime_version?: string;
  /** Install hint (shown when runtime not installed) */
  runtime_install_hint?: string;
  /** The runtime type this agent is configured to use */
  runtime_type: RuntimeType;
}

// ===========================================================================
// Workspace Browser types
// ===========================================================================

/** A single entry (file or directory) in a workspace directory listing */
export interface DirectoryEntry {
  name: string;
  is_dir: boolean;
  size: number;
  modified: number;
}

/** Content of a file from the workspace */
export interface FileContent {
  path: string;
  name: string;
  size: number;
  mime_type: string;
  content: string;
}

// ===========================================================================
// API Key Management types
// ===========================================================================

/** Masked API key info returned from the backend */
export interface ApiKeyInfo {
  /** Provider/runtime identifier (e.g. "claude-code") */
  id: string;
  /** Human-readable provider name */
  name: string;
  /** Masked key for display (e.g. "sk-***...xyz") */
  masked_key: string;
  /** Whether a key is currently stored */
  has_key: boolean;
}

// ===========================================================================
// Skill Management types
// ===========================================================================

/** Skill type classification */
export type SkillType = 'MCP Server' | 'Tool' | 'Custom Command';

/** Skill running status */
export type SkillStatus = 'Active' | 'Inactive' | 'Error' | 'Connecting';

/** A single Skill configuration */
export interface SkillInfo {
  /** Unique skill identifier */
  id: string;
  /** Agent this skill belongs to */
  agent_id: string;
  /** Human-readable skill name */
  name: string;
  /** Skill type */
  skill_type: SkillType;
  /** Skill configuration (flexible JSON) */
  config: Record<string, unknown>;
  /** Running status */
  status: SkillStatus;
  /** Creation timestamp (ISO 8601) */
  created_at: string;
  /** Last updated timestamp (ISO 8601) */
  updated_at: string;
}

// ===========================================================================
// Activity Log types
// ===========================================================================

/** Activity type enum */
export type ActivityType =
  | "agent_created"
  | "agent_deleted"
  | "conversation_started"
  | "conversation_ended"
  | "skill_changed"
  | "channel_created"
  | "channel_updated"
  | "channel_deleted"
  | "channel_message"
  | "system";

/** A single activity log entry */
export interface ActivityLogEntry {
  /** Unique identifier */
  id: string;
  /** ISO 8601 timestamp */
  timestamp: string;
  /** Type of activity */
  activity_type: ActivityType;
  /** Agent ID this relates to (if applicable) */
  agent_id: string | null;
  /** Workspace ID (if applicable) */
  workspace_id: string | null;
  /** Human-readable summary */
  summary: string;
  /** Additional details */
  details: Record<string, unknown>;
}

/** Paginated result of activity log entries */
export interface ListActivitiesResult {
  /** Activity entries (newest first) */
  entries: ActivityLogEntry[];
  /** Total count of matching entries (before pagination) */
  total: number;
}
