export type TabType = 'CHAT' | 'TASKS' | 'WORKSPACE' | 'SKILLS' | 'ACTIVITY' | 'PROFILE';

/** Message role in a conversation */
export type MessageRole = "user" | "agent" | "system";

/** Agent identifier */
export type AgentId = string;

export interface Agent {
  id: string;
  name: string;
  description: string;
  status: 'online' | 'offline' | 'busy';
  avatar: string;
  color: string;
}

// ===========================================================================
// Channel types
// ===========================================================================

/** A collaboration channel containing multiple Agent members. */
export interface Channel {
  id: string;
  name: string;
  members: ChannelMember[];
  messages: ChannelMessage[];
  /** Compressed summary of older messages (generated by Agent runtime) */
  summary?: string | null;
  /** Message ID up to which messages have been summarized */
  summary_up_to?: string | null;
  /** When the summary was last updated */
  summary_updated_at?: string | null;
  created_at: string;
  updated_at: string;
}

/** A member (Agent) in a channel. */
export interface ChannelMember {
  agent_id: string;
  role: string;
  joined_at: string;
}

/** A message within a channel. */
export interface ChannelMessage {
  id: string;
  channel_id: string;
  sender_type: "user" | "agent";
  sender_id: string;
  content: string;
  /** Structured content blocks (tool_use / tool_result) collected during agent execution. */
  content_blocks?: ContentBlock[];
  timestamp: string;
}

/** Lightweight channel info for listing. */
export interface ChannelInfo {
  id: string;
  name: string;
  member_count: number;
  unread_count: number;
  preview: string;
  message_count: number;
  created_at: string;
  updated_at: string;
}

/** Response from send_channel_message IPC. */
export interface SendChannelMessageResponse {
  /** The channel (with user message already persisted). */
  channel: Channel;
  /** Number of agents triggered by @mentions (0 = no agents). */
  agents_triggered: number;
}

export interface Thread {
  id: string;
  agent_id: string;
  title: string;
  session_id: string | null;
  messages: ThreadMessageData[];
  created_at: string;
  updated_at: string;
}

export interface ThreadMessageData {
  id: string;
  role: "user" | "agent";
  content: string;
  timestamp: string;
}

export interface ThreadInfo {
  id: string;
  agent_id: string;
  title: string;
  preview: string;
  message_count: number;
  created_at: string;
  updated_at: string;
  /** Agent display name (for global thread list) */
  agent_name?: string;
  /** Agent emoji (for global thread list) */
  agent_emoji?: string;
  /** Agent icon name (for global thread list) */
  agent_icon?: string | null;
}

// ===========================================================================
// Task types
// ===========================================================================

/** Task status enum */
export type TaskStatus = 'todo' | 'in_progress' | 'in_review' | 'done' | 'blocked' | 'cancelled';

/** Task priority (1=critical, 5=trivial) */
export type TaskPriority = 1 | 2 | 3 | 4 | 5;

/** Task execution mode */
export type TaskExecutionMode = 'realtime' | 'async';

/** Task creation source */
export type TaskSource = 'manual' | 'conversation' | 'agent_created' | 'subtask';

/** A Task in the system */
export interface Task {
  id: string;                    // UUID (TEXT), consistent with DB
  title: string;
  description: string;
  status: TaskStatus;
  priority: TaskPriority;
  creatorType: 'user' | 'agent';
  creatorId: string;            // Always populated: user_id or agent_id
  assigneeId?: string;          // agent_id
  channelId?: string;           // bound channel
  threadId?: string;            // bound thread
  parentTaskId?: string;        // parent task
  executionMode: TaskExecutionMode;
  source: TaskSource;
  sourceMessageId?: string;
  result?: string;
  createdAt: string;
  updatedAt: string;
  completedAt?: string;
  // Joined / computed fields
  childTaskCount: number;
  dependencyCount: number;
}

/** Task dependency relationship */
export interface TaskDependency {
  taskId: string;
  dependsOnId: string;
}

/** Task history entry */
export interface TaskHistoryEntry {
  id: number;
  taskId: string;
  field: string;
  oldValue?: string;
  newValue?: string;
  changedBy: string;
  changedAt: string;
}

/** Input for creating a new Task */
export interface CreateTaskInput {
  title: string;
  description?: string;
  priority?: TaskPriority;
  creatorId: string;             // Required: creator identifier
  creatorType?: 'user' | 'agent';
  assigneeId?: string;
  channelId?: string;
  threadId?: string;
  parentTaskId?: string;
  executionMode?: TaskExecutionMode;
  source?: TaskSource;
  sourceMessageId?: string;
}

/** Input for updating an existing Task */
export interface UpdateTaskInput {
  title?: string;
  description?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  assigneeId?: string | null;
  executionMode?: TaskExecutionMode;
  result?: string | null;
}

export interface Message {
  id: string;
  sender: {
    name: string;
    avatar: string;
    isAgent: boolean;
  };
  content: string;
  timestamp: string;
  isThinking?: boolean;
}

// ===========================================================================
// Agent Runtime types
// ===========================================================================

/** Agent runtime type enum */
export type RuntimeType =
  | "claude_code"
  | "codex"
  | "gemini"
  | string; // custom runtime types

/** Agent runtime status */
export type AgentRuntimeStatusType =
  | "available"
  | "unhealthy"
  | "not-installed"
  | "detecting";

/** Agent runtime capability */
export type AgentCapability =
  | "streaming"
  | "sessions"
  | "tool_use"
  | "structured_output";

/** Information about a registered agent runtime */
export interface AgentRuntimeInfo {
  id: string;
  name: string;
  runtime_category: string;
  runtime_type: RuntimeType;
  status: AgentRuntimeStatusType;
  version?: string;
  install_path?: string;
  capabilities: AgentCapability[];
  install_hint: string;
  binary_name?: string;
}

/** A structured content block from agent runtime output (tool_use or tool_result). */
export interface ContentBlock {
  type: "tool_use" | "tool_result";
  /** tool_use: unique id for matching with tool_result */
  id?: string;
  /** tool_use: tool name (e.g. "Read", "Write", "Bash") */
  name?: string;
  /** tool_use: tool input parameters */
  input?: Record<string, unknown>;
  /** tool_result: reference to the matching tool_use id */
  tool_use_id?: string;
  /** tool_result: result content (string or array of content items) */
  content?: string | unknown[];
}

/** Streaming event from an agent runtime execution */
export interface StreamEvent {
  text: string;
  is_done: boolean;
  error?: string;
  type?: string;
  session_id?: string;
  /** Structured content blocks (tool_use, tool_result) from verbose JSON output */
  content_blocks?: ContentBlock[];
}

/** Channel streaming chunk event (wraps StreamEvent with agent context) */
export interface ChannelChunkEvent {
  channel_id: string;
  agent_id: string;
  agent_index: number;
  total_agents: number;
  event: StreamEvent;
}

/** Channel agent start event */
export interface ChannelAgentStartEvent {
  channel_id: string;
  agent_id: string;
  agent_index: number;
  total_agents: number;
}

/** Channel response event (after streaming completes) */
export interface ChannelResponseEvent {
  channel_id: string;
  agent_id: string;
  content: string;
  /** Structured content blocks (tool_use / tool_result) collected during execution. */
  content_blocks?: ContentBlock[];
  session_id: string | null;
}

/** A2A trigger start event (when an Agent triggers another Agent via @{agent}) */
export interface ChannelA2aStartEvent {
  channel_id: string;
  agent_id: string;
  triggered_by: string;
  depth: number;
}

/** A2A depth exceeded event (when trigger chain reaches max depth) */
export interface ChannelA2aDepthExceededEvent {
  channel_id: string;
  agent_id: string;
  triggered_by: string;
  depth: number;
  max_depth: number;
}

/** Parsed @mention from a message */
export interface ParsedMention {
  raw: string;
  agent_id: string;
}

// ===========================================================================
// Agent Workspace types
// ===========================================================================

/** Agent summary returned from the backend */
export interface AgentSummary {
  agent_id: string;
  name: string;
  emoji: string;
  avatar: string | null;
  /** SVG icon name from the icon registry (e.g. "Bot", "Rocket") */
  icon: string | null;
  enabled: boolean;
  session_count: number;
  /** The runtime type this agent is bound to */
  runtime_type: RuntimeType;
  /** Connection mode: local (default) or remote */
  connection_mode: ConnectionMode;
}

/** Agent identity metadata */
export interface IdentitySummary {
  agent_id: string;
  name: string;
  emoji: string;
  avatar: string | null;
  /** SVG icon name from the icon registry */
  icon: string | null;
  creature: string;
  vibe: string;
  /** The runtime type this agent is bound to */
  runtime_type: RuntimeType;
  /** Connection mode: local or remote */
  connection_mode: ConnectionMode;
}

/** Request to create a new Agent */
export interface CreateAgentRequest {
  name: string;
  creature?: string;
  vibe?: string;
  emoji?: string;
  avatar?: string;
  /** SVG icon name from the icon registry */
  icon?: string;
  /** Runtime type for the agent (defaults to "claude_code") */
  runtime_type?: RuntimeType;
  /** Connection mode for the agent (defaults to "local") */
  connection_mode?: ConnectionMode;
}

/** Request to update an existing Agent's mutable properties */
export interface UpdateAgentRequest {
  name?: string;
  creature?: string;
  vibe?: string;
  emoji?: string;
  /** SVG icon name from the icon registry (empty string clears it) */
  icon?: string;
}

/** Health information for a single agent workspace */
export interface AgentHealthInfo {
  agent_id: string;
  workspace_exists: boolean;
  identity_file_exists: boolean;
  soul_file_exists: boolean;
  conversations_dir_exists: boolean;
  context_dir_exists: boolean;
  is_healthy: boolean;
  missing_items: string[];
}

/** Workspace and Agent manager status */
export interface ManagerStatus {
  total_agents: number;
  enabled_agents: number;
  active_agent_id: string | null;
  workspace_root: string;
  agents_health: AgentHealthInfo[];
}

/** Result of workspace initialization */
export interface InitWorkspaceResult {
  templates_created: string[];
  templates_skipped: string[];
  default_created: boolean;
}

/** Agent context information (for debugging/preview) */
export interface AgentContextResult {
  agent_id: string;
  system_prompt: string;
  has_user_context: boolean;
  has_agent_instructions: boolean;
  has_tool_instructions: boolean;
  has_memory: boolean;
  has_history: boolean;
  context_prefix_length: number;
}

// ===========================================================================
// Agent with Runtime status types
// ===========================================================================

/** Agent summary fused with its runtime availability status */
export interface AgentWithRuntime {
  /** Agent workspace summary */
  agent: AgentSummary;
  /** Runtime status: "available" | "not-installed" | "unhealthy" | "detecting" */
  runtime_status: AgentRuntimeStatusType;
  /** Detected runtime version (if available) */
  runtime_version?: string;
  /** Install hint (shown when runtime not installed) */
  runtime_install_hint?: string;
  /** The runtime type this agent is configured to use */
  runtime_type: RuntimeType;
}

// ===========================================================================
// Workspace Browser types
// ===========================================================================

/** A single entry (file or directory) in a workspace directory listing */
export interface DirectoryEntry {
  name: string;
  is_dir: boolean;
  size: number;
  modified: number;
}

/** Content of a file from the workspace */
export interface FileContent {
  path: string;
  name: string;
  size: number;
  mime_type: string;
  content: string;
}

// ===========================================================================
// API Key Management types
// ===========================================================================

/** Masked API key info returned from the backend */
export interface ApiKeyInfo {
  /** Provider/runtime identifier (e.g. "claude-code") */
  id: string;
  /** Human-readable provider name */
  name: string;
  /** Masked key for display (e.g. "sk-***...xyz") */
  masked_key: string;
  /** Whether a key is currently stored */
  has_key: boolean;
}

// ===========================================================================
// Skill Management types
// ===========================================================================

/** Skill type classification */
export type SkillType = 'MCP Server' | 'Tool' | 'Custom Command';

/** Skill running status */
export type SkillStatus = 'Active' | 'Inactive' | 'Error' | 'Connecting';

/** A single Skill configuration */
export interface SkillInfo {
  /** Unique skill identifier */
  id: string;
  /** Agent this skill belongs to */
  agent_id: string;
  /** Human-readable skill name */
  name: string;
  /** Skill type */
  skill_type: SkillType;
  /** Skill configuration (flexible JSON) */
  config: Record<string, unknown>;
  /** Running status */
  status: SkillStatus;
  /** Creation timestamp (ISO 8601) */
  created_at: string;
  /** Last updated timestamp (ISO 8601) */
  updated_at: string;
}

// ===========================================================================
// Activity Log types
// ===========================================================================

/** Activity type enum */
export type ActivityType =
  | "agent_created"
  | "agent_deleted"
  | "conversation_started"
  | "conversation_ended"
  | "skill_changed"
  | "channel_created"
  | "channel_updated"
  | "channel_deleted"
  | "channel_message"
  | "system";

/** A single activity log entry */
export interface ActivityLogEntry {
  /** Unique identifier */
  id: string;
  /** ISO 8601 timestamp */
  timestamp: string;
  /** Type of activity */
  activity_type: ActivityType;
  /** Agent ID this relates to (if applicable) */
  agent_id: string | null;
  /** Workspace ID (if applicable) */
  workspace_id: string | null;
  /** Human-readable summary */
  summary: string;
  /** Additional details */
  details: Record<string, unknown>;
}

/** Paginated result of activity log entries */
export interface ListActivitiesResult {
  /** Activity entries (newest first) */
  entries: ActivityLogEntry[];
  /** Total count of matching entries (before pagination) */
  total: number;
}

// ===========================================================================
// Task Suggestion types
// ===========================================================================

/** A single task suggested by an agent during a conversation */
export interface SuggestedTask {
  title: string;
  description: string;
  priority: number;
  assignee: string | null;
  dependencies: string[];
}

/** Task suggestion status */
export type TaskSuggestionStatus = 'pending' | 'confirmed' | 'dismissed';

/** Content payload for a task_suggestion message */
export interface TaskSuggestionContent {
  type: 'task_suggestion';
  suggestions: SuggestedTask[];
  status: TaskSuggestionStatus;
  confirmed_task_ids?: string[];
}

/** Event payload for task://suggested */
export interface TaskSuggestedEvent {
  channel_id: string;
  agent_id: string;
  message_id: string;
}

/** Event payload for task://suggested-confirmed */
export interface TaskSuggestedConfirmedEvent {
  channel_id: string;
  message_id: string;
  task_ids: string[];
}

/** Event payload for task://suggested-dismissed */
export interface TaskSuggestedDismissedEvent {
  channel_id: string;
  message_id: string;
}

// ===========================================================================
// Remote Connection types
// ===========================================================================

/** Connection mode for agents */
export type ConnectionMode =
  | "local"
  | { remote: { connection_id: string } };

/** Authentication type for remote connections */
export type RemoteAuthType = "none" | "api_key" | "oauth2";

/** Remote connection status */
export type RemoteConnectionStatus = "online" | "offline" | "error" | "unknown";

/** A remote A2A endpoint connection */
export interface RemoteConnectionInfo {
  id: string;
  name: string;
  endpoint_url: string;
  auth_type: RemoteAuthType;
  status: RemoteConnectionStatus;
  agent_card: RemoteAgentCard | null;
  last_health_check_at: string | null;
  created_at: string;
  updated_at: string;
}

/** Agent card from a remote endpoint */
export interface RemoteAgentCard {
  name: string;
  description?: string;
  endpoint?: string;
  capabilities: string[];
  supported_operations: string[];
  version?: string;
}

/** Result of testing a remote connection */
export interface TestConnectionResult {
  success: boolean;
  agent_card: RemoteAgentCard | null;
  error: string | null;
}

/** Request to create a remote connection */
export interface CreateRemoteConnectionRequest {
  name: string;
  endpoint_url: string;
  auth_type?: RemoteAuthType;
  api_key?: string;
}

/** Request to update a remote connection */
export interface UpdateRemoteConnectionRequest {
  name?: string;
  endpoint_url?: string;
  auth_type?: RemoteAuthType;
  api_key?: string;
}

// ===========================================================================
// Collaboration / A2A Multi-Agent types
// ===========================================================================

/** Delegation status */
export type DelegationStatusType =
  | 'PENDING'
  | 'SENT'
  | 'ACKNOWLEDGED'
  | 'IN_PROGRESS'
  | 'COMPLETED'
  | 'FAILED'
  | 'CANCELLED'
  | 'TIMED_OUT';

/** A task delegation between agents */
export interface DelegationInfo {
  id: string;
  from_agent_id: string;
  to_agent_id: string;
  task_description: string;
  context_summary: string;
  parent_task_id: string | null;
  channel_id: string | null;
  status: DelegationStatusType;
  target_connection_mode: ConnectionMode | null;
  result: string | null;
  error: string | null;
  created_at: string;
  updated_at: string;
}

/** Request to create a delegation */
export interface CreateDelegationRequest {
  from_agent_id: string;
  to_agent_id: string;
  task_description: string;
  context_summary: string;
  parent_task_id?: string;
  channel_id?: string;
}

/** Artifact info returned from backend */
export interface ArtifactInfo {
  id: string;
  producer_agent_id: string;
  name: string;
  file_path: string;
  content_hash: string | null;
  mime_type: string | null;
  created_at: string;
  task_id: string | null;
  description: string | null;
  size: number;
}

/** Artifact content result */
export interface ArtifactContentResult {
  artifact: ArtifactInfo;
  content: string;
}

/** Push notification config info */
export interface PushNotificationConfigInfo {
  id: string;
  url: string;
  has_token: boolean;
  has_hmac_secret: boolean;
  events: string[];
  active: boolean;
}

/** Push event payload for a2a://task-updated */
export interface PushEventPayload {
  event_id: string;
  event_type: string;
  agent_id: string;
  task_id: string;
  task_status: string;
  message: string;
  result: unknown;
  timestamp: string;
}

/** Push event payload for a2a://task-completed */
export interface PushTaskCompletedPayload {
  event_id: string;
  agent_id: string;
  task_id: string;
  message: string;
  result: unknown;
  timestamp: string;
}

/** Push event payload for a2a://task-failed */
export interface PushTaskFailedPayload {
  event_id: string;
  agent_id: string;
  task_id: string;
  message: string;
  result: unknown;
  timestamp: string;
}

/** Delegation created event */
export interface DelegationCreatedEvent {
  delegation_id: string;
  from_agent_id: string;
  to_agent_id: string;
}

// ===========================================================================
// LAN A2A Server types
// ===========================================================================

/** LAN A2A server status */
export type LanServerStatus = 'running' | 'stopped' | { error: string };

/** Information about the running LAN A2A server */
export interface LanServerInfo {
  /** Status of the server */
  status: LanServerStatus;
  /** Port the server is bound to */
  port: number;
  /** Local IP addresses that can reach this server */
  local_ips: string[];
  /** URL for the agent card endpoint */
  agent_card_url: string | null;
}

// ===========================================================================
// Bridge Workspace types (remote workspace gateway)
// ===========================================================================

/** Remote workspace info from bridge.getWorkspaceInfo */
export interface BridgeWorkspaceInfo {
  workspace_root: string;
  total_agents: number;
  enabled_agents: number;
  active_agent_id: string | null;
}

/** Remote agent info from bridge.getAgents */
export interface BridgeAgent {
  agent_id: string;
  name: string;
  emoji: string;
  creature: string;
  vibe: string;
  runtime_type: string;
}

/** File entry from bridge.listFiles */
export interface BridgeFileEntry {
  name: string;
  is_dir: boolean;
  size: number;
  modified: number;
}

/** File content from bridge.readFile */
export interface BridgeFileContent {
  name: string;
  size: number;
  mime_type: string;
  content: string;
}
